version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL:leopucci@gmail.com

    env_file:
      - C:\nginx-certbot\nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - C:\nginx-certbot\user_conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets: